<?php if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_60dd82b6d1c8d',
		'title' => 'Feature Columns',
		'fields' => array(
			array(
				'key' => 'field_60dd82c40045e',
				'label' => 'Column 1 Icon',
				'name' => 'column_1_icon',
				'type' => 'text',
				'instructions' => 'Font Awesome 4 icon.
The format is "fa fa-iconname"',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fa fa-check',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd8f36f1d6c',
				'label' => 'Column 1 Title',
				'name' => 'column_1_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Column Title',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd932dc33b1',
				'label' => 'Column 1 Text',
				'name' => 'column_1_text',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam totam nobis necessitatibus labore quia cumque placeat non fugiat voluptates deleniti asperiores sit hic qui neque, dolores quos a suscipit eum.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_60dd9363c33b3',
				'label' => 'Column 2 Icon',
				'name' => 'column_2_icon',
				'type' => 'text',
				'instructions' => 'Font Awesome 4 icon.
The format is "fa fa-iconname"',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fa fa-shopping-cart',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd937cc33b5',
				'label' => 'Column 2 Title',
				'name' => 'column_2_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Column Title',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd9382c33b7',
				'label' => 'Column 2 Text',
				'name' => 'column_2_text',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam totam nobis necessitatibus labore quia cumque placeat non fugiat voluptates deleniti asperiores sit hic qui neque, dolores quos a suscipit eum.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_60dd9360c33b2',
				'label' => 'Column 3 Icon',
				'name' => 'column_3_icon',
				'type' => 'text',
				'instructions' => 'Font Awesome 4 icon.
The format is "fa fa-iconname"',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fa fa-users',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd937cc33b4',
				'label' => 'Column 3 Title',
				'name' => 'column_3_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Column Title',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd9381c33b6',
				'label' => 'Column 3 Text',
				'name' => 'column_3_text',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam totam nobis necessitatibus labore quia cumque placeat non fugiat voluptates deleniti asperiores sit hic qui neque, dolores quos a suscipit eum.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/feature-cols',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_60db1fbee8c2c',
		'title' => 'Feature Container',
		'fields' => array(
			array(
				'key' => 'field_60db1fd1b9f27',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image to be displayed in the container. Recommended to be about equal in width and height.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '0.5',
				'mime_types' => '',
			),
			array(
				'key' => 'field_60db2076b9f28',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Container title',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60db20a8b9f29',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat sed, beatae exercitationem quam similique, voluptates fuga repellat cumque reiciendis labore adipisci. Itaque nihil voluptatum eum. Reprehenderit libero corporis molestias! Facilis pariatur recusandae rerum deserunt cumque excepturi aliquam commodi numquam iusto.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_60db20cfb9f2a',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => 'Text that will be displayed on the button. Leave empty to remove button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Button Text',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60db2c197743e',
				'label' => 'Button Color',
				'name' => 'button_color',
				'type' => 'select',
				'instructions' => 'Pick a different color than background!',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'button-primary' => 'Primary',
					'button-secondary' => 'Secondary',
					'button-gray-200' => 'Light',
					'button-gray-900' => 'Dark',
				),
				'default_value' => 'button-secondary',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_60db21441144d',
				'label' => 'Background Color',
				'name' => 'background_color',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'bg-primary' => 'Primary',
					'bg-secondary' => 'Secondary',
					'bg-gray-100' => 'Light',
					'bg-gray-900' => 'Dark',
				),
				'default_value' => 'bg-primary',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_60db21c05e1c9',
				'label' => 'Image Position',
				'name' => 'image_position',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Image on left',
					'right' => 'Image on right',
				),
				'default_value' => 'flex-md-row',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/feature-container',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_60dd9a40e4aa8',
		'title' => 'Hero Image',
		'fields' => array(
			array(
				'key' => 'field_60dd9a6e4594d',
				'label' => 'Image',
				'name' => 'hero_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => 1,
				'mime_types' => '',
			),
			array(
				'key' => 'field_60ddc30d8d5ac',
				'label' => 'Image Position',
				'name' => 'hero_image_position',
				'type' => 'range',
				'instructions' => 'background-position-y property. <br>
How far up/down the image will be displayed (0% for top, 100% for bottom)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 30,
				'min' => '',
				'max' => '',
				'step' => '',
				'prepend' => '',
				'append' => '%',
			),
			array(
				'key' => 'field_60dd9b104594e',
				'label' => 'Title',
				'name' => 'hero_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Witchcraft Theme',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd9b244594f',
				'label' => 'Subtitle',
				'name' => 'hero_subtitle',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'A theme for witches and wizards. Made for WordPress blogs and WooCommerce stores.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_60dd9b6945950',
				'label' => 'Button Text',
				'name' => 'hero_button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Read More',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60dd9b7245951',
				'label' => 'Button Color',
				'name' => 'hero_button_color',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'button-primary' => 'Primary',
					'button-secondary' => 'Secondary',
					'button-gray-200' => 'Light',
					'button-gray-900' => 'Dark',
				),
				'default_value' => 'button-secondary',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_60dd9bcd45952',
				'label' => 'Button Link',
				'name' => 'hero_button_link',
				'type' => 'text',
				'instructions' => 'Value in a href="" tag.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
